from typing import Protocol

class Switch(Protocol):
    def close_channel(self, channel: int) -> None: ...
    def open_channel(self, channel: int) -> None: ...
    def open_all(self) -> None: ...

class CurrentSource(Protocol):
    def set_current(self, current: float) -> None: ...
    def set_output(self, state: bool) -> None: ...

class Voltmeter(Protocol):
    def measure_voltage(self) -> float: ...
